name: cleaning3.9
channels:
    - intel
    - conda-forge
    - r
    - bioconda
dependencies:
    - python=3.9
    - numpy
    - matplotlib
    - seaborn
    - pandas=1
    - scikit-learn
    - pip
    - requests
    - r-base
    - r-essentials 
    - tornado
    - numexpr
    - pyarrow
    - pytables
    - pyreadstat
    - rpy2
    - simplejson
    - seqkit
    - llvmlite
    - dask
    - pip:
        - beautifulsoup4
        - csvkit
        - fuzzy
        - gensim
        - h5py
        - jupyter
        - jupyterlab
        - lxml
        - Metaphone
        - nltk
        - xlrd
        - openpyxl
        - psycopg2
        - pymongo
        - rise
        - sqlalchemy
        - sqlalchemy-utils
        - vaex
        - umap-learn
        - imbalanced-learn
        - toml
        - pytest
